apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
- monitors.yaml
images:
- name: morphicworld/morphiccommunity
  newName: morphicworld/morphiccommunity
  newTag: stable-20200930.16
